fix: Added qwt6 path for OpenSuse repo install
hyOzd/serialplot pull request #13
Opened 2021-09-14 08:48 UTC by ZehDeckel

In OpenSuse Leap 15.2 (and maybe others), the qwt6 header files
installed via zypper are located in /usr/include/qwt6

I also got a warning about if-endif mismatch, so I did a quick change there.

Not included in this pull request, but one could add the required packages available from the OpenSuse repository to the Readme. While maybe not minimal, I used `libqt5-qtbase-devel qwt6-devel qwt6-qt5-devel libqt5-qtserialbus-devel libqt5-qtserialport-devel` with zypper.

2021-09-15 08:13 UTC, hyOzd requested changes
If you add build instructions for opensuse to the Readme, I would approve that as well.

2021-09-15 08:13 UTC, hyOzd commented on cmake/modules/FindQwt.cmake
> +#endif (QWT_LIBRARY)
Please remove the commented line.

2021-09-16 12:48 UTC, ZehDeckel commented
I have removed the commented line and added OpenSUSE instructions to the readme file.

2021-09-17 06:16 UTC, merged

2021-09-17 06:17 UTC, hyOzd commented
@ZehDeckel Thanks for your contribution.